# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652743145452e4cabea11a24b1d477e8243b55734a8e544350e56e4322f378417797fa3ac5532d50d1d923678b77b92e4147bc1f72e6a352b45a19ac6b97f23a

test:
  secret_key_base: 87a5093e84693e099e2bb65c165b8c669c5f43d2825b0b0b0de0fc953dcbed7b37215f5199cabaf46f4a464df74106436f9ddfd0cc276ad93b616f4121c6edf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
